{% set name = "cyipopt" %}
{% set version = "0.1.7" %}
{% set sha256 = "e62d4265743078c60f0af1426218310a9fbc1b6d0d0e60879e172d569dd3343d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/matthias-k/cyipopt/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - no_link_gfortran.patch

build:
  number: 2
  # TODO: Once ipopt is available for Windows in conda forge, remove the
  # following line.
  skip: True  # [win]
  script:  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - pkg-config  # [osx]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - ipopt
    - setuptools
    - cython
    - numpy
    - scipy
    - six
  run:
    - python
    - ipopt
    - {{ pin_compatible('numpy') }}
    - scipy
    - six
    - future

test:
  imports:
    - ipopt
  files:
    - examplehs071.py
  commands:
    - python examplehs071.py

about:
  home: https://github.com/matthias-k/cyipopt
  license: EPL-1.0
  summary: 'A Cython wrapper to the IPOPT optimization package'

  description: |
    Ipopt (Interior Point OPTimizer, pronounced eye-pea-Opt) is a software
    package for large-scale nonlinear optimization. cyipopt is a python wrapper
    around Ipopt. It enables using Ipopt from the comfort of the great Python
    scripting language. Ipopt is available from the COIN-OR initiative, under
    the Eclipse Public License (EPL).
  doc_url: http://pythonhosted.org/ipopt/
  dev_url: https://github.com/matthias-k/cyipopt

extra:
  recipe-maintainers:
    - moorepants
