# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "goHKEXj+5rxuoYdrxkreOvBxB023S9L/gQ8fgV9zaE7h/VK/Bhryckv77gt0DQmeU3PZVHxPfGI0K0+HaH1zUajpuUU0P+Aqq74Ei6ra3HRAkviL0OJhXGB8F7jgbMtMaIKVc2XyUCdpQ28He3Cu7+1voL5v04hWM/busu/yXfIidU3ko7i7+9NuKNRcmGECmvupc5c1aRiRcVne0p6o4TW/O0l0lGhcK37qaCXfheNGRdXg75ZqtezW2BMwHlObQg6i7WnFlsFJ24u73Ap9GKXCN+0ZPZhzoObgRdg3F5t6PHwxFd+8lnl6PTmZbldLS3Nae76wMBCBgscdjWOEAsP/D1blu9Emn1TrmxMKft0lzurGERMw8me6qr8fceNke6ce8TQPVlfA6Hg2QBPCXzHF7j1ofK+ubasstQ+DZtMJng6GEnFW/NBKHY4HRS9nK+d9Ws6ySItm5u4lphPjB8oWWRYRPDfMxvxtHXPLacz/aGntUrWAMo4806Tr4d/7kEY9w0zb7i5l/NpUD+6tgmWM5LsRRLNK7yFiJCr92WwOJhjXpVnr89WTtjTWxMHfe9Ym2A0o35qKHfJmLFedu36uKqlXBEvEThSMaL5piZwUJILJHQTj+IKs9BM15TBWq1FH4BQAzNln6HvnI1bSEkipTd5myt/EDYTRNXt85Lc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
