travis:
  secure:
    BINSTAR_TOKEN: GGCHWOl9s1laaPzJL1V1SFQEeBrq0jrQB5UP8x1XC76Tal/KwrvRp/R0d0JrsOfL/sIAnwHexX0zj+vkNLy58cqHPIan1WWt7Sxx1WpsP80wgPXSjT6u98tI4wfmnP42HVKfvjweM2SuFLT3JNvxzFD/UeuBTkJToUX5hbHLSL6Ww4pHlc66KyO2+Om7nIMwezPyP9UYhTAyFLkBeBUXp4q4Etx4vnOCDJyXci321b4qC6JBYmtrwfAUpxrNJygOSG62eUfMdKf7ft1kYAQ0XTqO2bVnmWE46MDX/51qbAhCZ3KJ8geTAV6slgRyrjGDZRSCd++6+uAr139PP8jiCXsrOvfimfSS/+j3F2qLBCplP++thcDl/7u+GnPXFKsOVaX0QZyasZB7KO5Ctt+rNFr+HH4920jAzuDEyMb2mbpNBk0FbK9yl2oCAEBQpO95JxbGjrM8MevkdWdCbTHy1VUkVGyKkjH0V7luYukzWIb5MYGataWlm3MWGIy9LXpceTNywBozQ+0WwSIWQ+UF/19jNAFpM4tIJ73pcGGKw9Mdvdv148kC7K+qpWAiA7zuQ1ydpnzWHwC1WUNvfutP8B9//k+Rsga3CfLi8EIRbTRPMUQ0MbaGRjtnK55WS0xo+J+Ln0gH1iPvdTnsdaFI4Fq9d5dh44UC+f5qNnTGUAE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
